blank_issues_enabled: false
contact_links:
  - name: 个人主页 / Homepage
    url: https://Zero-Ljh.github.io
    about: 访问李军辉的个人主页
  - name: 邮箱 / Email
    url: mailto:2430132207@qq.com
    about: 直接发邮件联系
